# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-06 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180506_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('can_mark_add', 'Author Add'),)},
        ),
    ]
