# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-06 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180507_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('can_author_add', 'Author Add'), ('can_author_delete', 'Author delete'), ('can_author_update', 'Author update'))},
        ),
    ]
