# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-06 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20180507_0301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_add_book', 'Add a book'), ('can_delete_book', 'Delete a book'), ('can_update_book', 'Update a book'))},
        ),
    ]
